### ISSUE TITLE
Can't run train.py

### ISSUE THREAD

**Issue by CeLuigi** [beopst/dcn.tf#6]
I tried to run your code using TensorFlow r0.10 and I get the following error message:

```
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 150, in main
    train()
  File "train.py", line 57, in train
    logits, hint_loss = model.inference(trn_x)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/models/dcn.py", line 211, in inference
    coarse_features = coarse_layers(inputs)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/models/dcn.py", line 31, in coarse_layers
    out = ops.conv2d(inputs, 12, [7,7], stride=2, padding='VALID', scope='coarse_conv1')
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/ops.py", line 204, in conv2d
    outputs = batch_norm(conv, **batch_norm_params)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/ops.py", line 109, in batch_norm
    initializer=tf.ones)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/luigi/Computer_vision/workspace/try_tensorflow/dcn.tf/slim/variables.py", line 225, in variable
    trainable=trainable, collections=collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1013, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 840, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 345, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 330, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 676, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 215, in __init__
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 288, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 666, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones() got an unexpected keyword argument 'partition_info'
```

Any suggestion are welcome

**Comment by beopst** [comment]
Sorry for the late response. I cannot reproduce the error you reported. I also use tf 0.10.0rc0.

**Comment by beopst** [comment]
I just realized that the error you reported is due to API changes. 
I don't know if it's too late, but please refer to my recent commit a225b60db2c2a8246da996e2edc74e07f20da86d.

**Comment by CeLuigi** [comment]
Don't worry, I have been able to solve the problem and run your code. Thanks for the reply

**Comment by rghv96** [comment]
Facing similar error. What's the fix?
