### ISSUE TITLE
Error running train.py with tensorflow 0.12

### ISSUE THREAD

**Issue by yunhunJang** [beopst/dcn.tf#7]
Hi, I'm trying to do some experiments with dynamic capacity networks. 
I prepared the dataset, but running ```train.py``` does not work with following error.
It seems that batch_norm caused the error.
Any suggestions to fix this problem?

Thanks!

```
Traceback (most recent call last):
  File "train.py", line 153, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 150, in main
    train()
  File "train.py", line 57, in train
    logits, hint_loss = model.inference(trn_x)
  File "/home/yhoon/dcn.tf/models/dcn.py", line 211, in inference
    coarse_features = coarse_layers(inputs)
  File "/home/yhoon/dcn.tf/models/dcn.py", line 31, in coarse_layers
    out = ops.conv2d(inputs, 12, [7,7], stride=2, padding='VALID', scope='coarse_conv1')
  File "/home/yhoon/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/yhoon/dcn.tf/slim/ops.py", line 204, in conv2d
    outputs = batch_norm(conv, **batch_norm_params)
  File "/home/yhoon/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/yhoon/dcn.tf/slim/ops.py", line 109, in batch_norm
    initializer=tf.ones)
  File "/home/yhoon/dcn.tf/slim/scopes.py", line 129, in func_with_args
    return func(*args, **current_args)
  File "/home/yhoon/dcn.tf/slim/variables.py", line 225, in variable
    trainable=trainable, collections=collections)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones() got an unexpected keyword argument 'partition_info'
```

**Comment by beopst** [comment]
Sorry for the late response. The error comes from a change of APIs. 
I fixed to deal with TF v0.12. Please refer to the recent commit a225b60db2c2a8246da996e2edc74e07f20da86d.
